In [84]:
import pandas as pd
import numpy as np

In [85]:
## data reading 
cs = pd.read_csv('D:\infosys project\DataSet\GlobalWeatherRepository.csv')

<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
C:\Users\siddh\AppData\Local\Temp\ipykernel_4532\2288884551.py:2: SyntaxWarning: invalid escape sequence '\i'
  cs = pd.read_csv('D:\infosys project\DataSet\GlobalWeatherRepository.csv')

In [86]:
cs.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [140]:
cs.shape

(122576, 34)

In [88]:
cs.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [ ]:
cs.info()

In [90]:
cs['calculate_kph'] = (cs['wind_kph'] * 0.621371)
cs[['wind_kph', 'wind_mph', 'calculate_kph']].head()
cs['calculate_visibility_km'] = (cs['visibility_miles'] * 1.60934).round()
cs[['calculate_visibility_km', 'visibility_km', 'visibility_miles']].head()
cs['calculated_fahrenheit'] = (cs['temperature_celsius'] * 9/5) + 32
cs[['calculated_fahrenheit', 'temperature_celsius']].head()
cs.drop(columns='temperature_fahrenheit', inplace= True)

## deletiing the redandent data

In [91]:
drop_columns_list = [
    'feels_like_fahrenheit', 
    'wind_mph', 
    'gust_mph', 
    'visibility_miles', 
    'pressure_in', 
    'precip_in'
]

cs.drop(columns = drop_columns_list, inplace= True)

In [97]:
cs.drop(columns = ['calculate_kph','calculate_visibility_km','calculated_fahrenheit'], inplace= True)

### Rename the column name

In [ ]:
new_columns_name = []
for i in cs.columns:
    new_columns_name.append((i.upper()))

In [105]:
cs.columns = new_columns_name
cs.head()

,COUNTRY,LOCATION_NAME,LATITUDE,LONGITUDE,TIMEZONE,LAST_UPDATED_EPOCH,LAST_UPDATED,TEMPERATURE_CELSIUS,CONDITION_TEXT,WIND_KPH,...,AIR_QUALITY_PM2.5,AIR_QUALITY_PM10,AIR_QUALITY_US-EPA-INDEX,AIR_QUALITY_GB-DEFRA-INDEX,SUNRISE,SUNSET,MOONRISE,MOONSET,MOON_PHASE,MOON_ILLUMINATION
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

## Checking about the duplicate and null values

In [139]:
cs.isnull().sum()
cs.duplicated().sum()

np.int64(0)

## checking about the statistical values

In [ ]:
cs.describe()

## Indivisual Column work with min and max value

In [ ]:
air_quality_columns = ['AIR_QUALITY_CARBON_MONOXIDE', 'AIR_QUALITY_SULPHUR_DIOXIDE', 'AIR_QUALITY_PM10' ]
for i in air_quality_columns:
    cs.loc[cs[i] < 0, i] = np.nan
print(cs[air_quality_columns].isnull().sum())

## fill the value with median with
for i in air_quality_columns:
    median_value = cs[i].median()
    cs[i].fillna(median_value, inplace =True)

In [ ]:
## remove the Outliers

outiler_list = ['WIND_KPH', 'GUST_KPH']

for i in outiler_list:
    cs.loc[cs[i] > 750, i] = np.nan

    cs[i].fillna(cs[i].median(), inplace= True)

### remove outliers from the pressure MB

cs.loc[cs['PRESSURE_MB'] > 1300, 'PRESSURE_MB'] = np.nan
cs['PRESSURE_MB'].fillna(cs['PRESSURE_MB'].median(), inplace= True)


### removing the outliers from Air Qulity PM

cs.loc[cs['AIR_QUALITY_PM10'] > 1600 , 'AIR_QUALITY_PM10'] = np.nan
cs['AIR_QUALITY_PM10'].fillna(cs['AIR_QUALITY_PM10'].median(), inplace= True)

### removing the outliers from Air_quality_carbon_monoxide

cs.loc[cs['AIR_QUALITY_CARBON_MONOXIDE'] > 1600 , 'AIR_QUALITY_CARBON_MONOXIDE'] = np.nan
cs['AIR_QUALITY_CARBON_MONOXIDE'].fillna(cs['AIR_QUALITY_CARBON_MONOXIDE'].median(), inplace= True)

## chaning in the data type

In [93]:
cs['last_updated'] = pd.to_datetime(cs['last_updated'])

In [174]:
cs.to_csv('Final_Clean_Data.csv', index=False)